services:
  postgres:
    image: postgres:18.1
    container_name: next-admin_postgres
    ports:
      - 55432:5432
    volumes:
      - ./infra/postgres/sql/:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - next-admin-network
  ses:
    image: oven/bun:1
    container_name: next-admin_ses
    ports:
      - 58005:8005
    command: bunx aws-ses-v2-local --host=0.0.0.0
    networks:
      - next-admin-network

volumes:
  postgres-data:
    external: false
  localstack-volume:
    external: false

networks:
  next-admin-network:
    driver: bridge
